const contactCta = {
  it: {
    label: 'Parla del tuo progetto USA',
    note: 'Condividi prodotto, canale desiderato e stato attuale del progetto. La prima risposta qualifica priorita, rischi e prossimi passi.',
  },
  en: {
    label: 'Discuss your US project',
    note: 'Share the product, target channel, and current stage. The first response qualifies priorities, risks, and next steps.',
  },
};

export const seoPages = {
  usaMarketEntryItalianCompanies: {
    path: '/usa-market-entry-italian-companies',
    keywords: 'USA market entry Italian companies, Italian companies US market, consulente ingresso mercato USA, export USA aziende italiane',
    it: {
      title: 'USA Market Entry per Aziende Italiane | Gianluca Piazza',
      description: 'Consulenza per aziende italiane che vogliono entrare nel mercato USA con strategia, canali commerciali, distributori, retail partnership e supporto operativo.',
      hero: 'USA Market Entry per Aziende Italiane',
      subtitle: 'Strategia, canali e sviluppo commerciale per portare prodotti italiani nel mercato americano.',
      answer: 'Per entrare negli Stati Uniti non basta tradurre l\'offerta: serve validare domanda, canali, margini, readiness commerciale e partner locali. Gianluca Piazza supporta aziende italiane nella costruzione di un percorso USA concreto, dal posizionamento iniziale alla relazione con buyer, distributori e partner.',
      processTitle: 'Come viene costruito il percorso',
      process: [
        'Diagnosi del prodotto, categoria, prezzo, canale e vincoli operativi.',
        'Mappatura dei segmenti USA piu coerenti con la proposta italiana.',
        'Preparazione di messaggi, materiali e criteri di qualifica per buyer e partner.',
        'Sviluppo di conversazioni commerciali con distributori, retailer o operatori locali.',
        'Supporto nella negoziazione iniziale e nella trasformazione delle opportunita in azioni operative.',
      ],
      proofTitle: 'Perche un approccio dedicato',
      proof: [
        'Esperienza su internazionalizzazione, business development e partnership strategiche.',
        'Metodo orientato a decisioni pratiche, non solo a report di mercato.',
        'Attenzione a readiness, posizionamento e sostenibilita del canale prima dell\'outreach.',
        'Contenuti e risposte strutturati per buyer umani e sistemi AI-search.',
      ],
      faqs: [
        ['Quali aziende italiane possono usare questo servizio?', 'Aziende con un prodotto gia validato, capacita di fornitura e interesse a testare canali USA come distribuzione, retail, partnership o presenza commerciale locale.'],
        ['Serve gia una societa negli Stati Uniti?', 'Non necessariamente. La scelta dipende da canale, rischio, contratti e operativita. Il percorso aiuta a capire quando una struttura locale diventa utile.'],
        ['Il lavoro include contatto con partner USA?', 'Si, quando l\'azienda e pronta per l\'outreach. Prima vengono chiariti target, proposta, materiali e criteri di qualifica.'],
      ],
      cta: contactCta.it,
    },
    en: {
      title: 'USA Market Entry for Italian Companies | Gianluca Piazza',
      description: 'Consulting for Italian companies entering the US market through strategy, commercial channels, distributors, retail partnerships, and operating support.',
      hero: 'USA Market Entry for Italian Companies',
      subtitle: 'Strategy, channels, and business development to bring Italian products into the American market.',
      answer: 'Entering the United States requires more than translating the offer: companies must validate demand, channels, margins, commercial readiness, and local partners. Gianluca Piazza helps Italian companies build a practical US path from positioning to conversations with buyers, distributors, and partners.',
      processTitle: 'How the path is built',
      process: [
        'Diagnosis of product, category, price, channel, and operating constraints.',
        'Mapping of the US segments that best fit the Italian offer.',
        'Preparation of messaging, materials, and qualification criteria for buyers and partners.',
        'Business development conversations with distributors, retailers, or local operators.',
        'Support in early negotiation and in turning opportunities into operating actions.',
      ],
      proofTitle: 'Why a dedicated approach',
      proof: [
        'Experience across internationalization, business development, and strategic partnerships.',
        'Decision-oriented method, not only market reporting.',
        'Focus on readiness, positioning, and channel sustainability before outreach.',
        'Content and answers structured for human buyers and AI-search systems.',
      ],
      faqs: [
        ['Which Italian companies is this for?', 'Companies with a validated product, supply capability, and interest in testing US channels such as distribution, retail, partnerships, or local commercial presence.'],
        ['Do we need a US company already?', 'Not always. The choice depends on channel, risk, contracts, and operations. The process clarifies when a local structure becomes useful.'],
        ['Does the work include contact with US partners?', 'Yes, when the company is ready for outreach. Targeting, proposition, materials, and qualification criteria come first.'],
      ],
      cta: contactCta.en,
    },
  },
  businessDevelopmentUsa: {
    path: '/business-development-usa',
    keywords: 'business development USA, sviluppo commerciale Stati Uniti, consulente business development America, partnership commerciali USA',
    it: {
      title: 'Business Development USA | Gianluca Piazza',
      description: 'Sviluppo commerciale negli Stati Uniti per aziende italiane: partner, buyer, pipeline, canali e negoziazione iniziale.',
      hero: 'Business Development USA',
      subtitle: 'Un presidio commerciale per trasformare interesse USA in conversazioni, partner e opportunita qualificate.',
      answer: 'Il business development USA collega strategia e mercato: identifica interlocutori rilevanti, testa la proposta, qualifica interesse e costruisce pipeline commerciale senza confondere attivita con risultato. Il focus e creare occasioni reali e leggibili per aziende italiane che vogliono crescere negli Stati Uniti.',
      processTitle: 'Attivita principali',
      process: [
        'Definizione ICP, canale prioritario e messaggio commerciale.',
        'Lista qualificata di account, distributori, buyer o partner potenziali.',
        'Outreach mirato con narrativa adatta al mercato americano.',
        'Gestione delle prime conversazioni e raccolta feedback dal mercato.',
        'Raccomandazioni su next step, materiali, pricing e readiness operativa.',
      ],
      proofTitle: 'Cosa rende utile il lavoro',
      proof: [
        'Unisce ricerca, vendita consulenziale e comprensione del contesto italiano.',
        'Riduce dispersione su contatti non coerenti con categoria, prezzo o canale.',
        'Traduce feedback commerciale in decisioni di prodotto, offerta e priorita.',
        'Mantiene visibilita su opportunita, rischi e azioni richieste all\'azienda.',
      ],
      faqs: [
        ['Il servizio crea una rete vendita USA?', 'Puo aiutare a impostarla, ma parte dalla qualifica di canali e partner prima di costruire una struttura piu stabile.'],
        ['Quanto e personalizzato l\'outreach?', 'L\'outreach viene costruito su categoria, proposta di valore, ruolo del contatto e obiettivo della conversazione.'],
        ['E adatto anche a servizi B2B?', 'Si, quando esiste una proposta chiara e un target USA identificabile. Il metodo si adatta a prodotti, servizi e partnership.'],
      ],
      cta: contactCta.it,
    },
    en: {
      title: 'Business Development USA | Gianluca Piazza',
      description: 'US business development for Italian companies: partners, buyers, pipeline, channels, and early-stage negotiation.',
      hero: 'Business Development USA',
      subtitle: 'A commercial presence to turn US interest into qualified conversations, partners, and opportunities.',
      answer: 'US business development connects strategy with the market: it identifies relevant counterparts, tests the proposition, qualifies interest, and builds a commercial pipeline without confusing activity with results. The focus is to create real, readable opportunities for Italian companies growing in the United States.',
      processTitle: 'Core activities',
      process: [
        'Definition of ICP, priority channel, and commercial message.',
        'Qualified list of accounts, distributors, buyers, or potential partners.',
        'Targeted outreach with a narrative adapted to the American market.',
        'Management of early conversations and collection of market feedback.',
        'Recommendations on next steps, materials, pricing, and operating readiness.',
      ],
      proofTitle: 'What makes the work useful',
      proof: [
        'Combines research, consultative selling, and understanding of Italian companies.',
        'Reduces dispersion across contacts that do not fit category, price, or channel.',
        'Turns commercial feedback into product, offer, and priority decisions.',
        'Keeps visibility on opportunities, risks, and actions required from the company.',
      ],
      faqs: [
        ['Does this create a US sales network?', 'It can help set one up, but it starts by qualifying channels and partners before building a more stable structure.'],
        ['How personalized is the outreach?', 'Outreach is built around category, value proposition, contact role, and the objective of the conversation.'],
        ['Is it suitable for B2B services too?', 'Yes, when there is a clear proposition and an identifiable US target. The method adapts to products, services, and partnerships.'],
      ],
      cta: contactCta.en,
    },
  },
  ricercaDistributoriUsa: {
    path: '/ricerca-distributori-usa',
    keywords: 'ricerca distributori USA, distributori Stati Uniti prodotti italiani, importatori USA, canali distribuzione America',
    it: {
      title: 'Ricerca distributori USA per aziende italiane | GP & Partners',
      description: 'GP & Partners aiuta aziende italiane ed europee a identificare, qualificare e attivare distributori USA con un processo operativo, non una lista di contatti generici.',
      hero: 'Ricerca distributori USA',
      subtitle: 'Trova distributori USA che possono davvero portare il tuo prodotto sul mercato.',
      answer: 'Non cerchiamo nomi in database massivi. Costruiamo una short list qualificata, prepariamo il messaggio commerciale, apriamo conversazioni e filtriamo chi ha margine, canale e interesse reale.',
      processTitle: 'Metodo di qualifica',
      process: [
        'Definizione del profilo distributore ideale e dei canali da evitare.',
        'Mappatura di importatori, distributori, agenti, broker o partner ibridi.',
        'Valutazione di fit su categoria, copertura, portfolio e modello operativo.',
        'Preparazione di materiali sintetici per apertura conversazione.',
        'Outreach, raccolta feedback e shortlist di opzioni perseguibili.',
      ],
      proofTitle: 'Controlli utili prima di scegliere',
      proof: [
        'Allineamento tra prezzo italiano, margine richiesto e prezzo finale USA.',
        'Verifica della coerenza tra territorio coperto e obiettivi dell\'azienda.',
        'Attenzione a esclusiva, minimo d\'ordine, promozione e responsabilita commerciali.',
        'Valutazione del distributore come partner, non solo come contatto in lista.',
      ],
      faqs: [
        ['La ricerca include importatori?', 'Si, se l\'importatore e il canale corretto per categoria e modello operativo. In alcuni casi servono agenti, broker o partner retail.'],
        ['Posso chiedere distributori per uno Stato specifico?', 'Si. La segmentazione puo essere nazionale, regionale o focalizzata su aree prioritarie come Florida, resto degli Stati Uniti e Caraibi quando il progetto lo richiede.'],
        ['Vengono garantiti contratti?', 'No. Il lavoro qualifica opportunita e conversazioni; i contratti dipendono da fit, condizioni, prodotto, readiness e negoziazione.'],
      ],
      cta: contactCta.it,
    },
    en: {
      title: 'US Distributor Search for Italian Companies | GP & Partners',
      description: 'GP & Partners helps Italian and European companies identify, qualify, and activate US distributors through an operating process, not a list of generic contacts.',
      hero: 'US Distributor Search',
      subtitle: 'Find US distributors who can actually take your product to market.',
      answer: 'We do not pull names from bulk databases. We build a qualified short list, prepare the commercial message, open conversations, and filter for counterparts with real margin, channel, and interest.',
      processTitle: 'Qualification method',
      process: [
        'Definition of the ideal distributor profile and channels to avoid.',
        'Mapping of importers, distributors, agents, brokers, or hybrid partners.',
        'Fit assessment on category, coverage, portfolio, and operating model.',
        'Preparation of concise materials for the first conversation.',
        'Outreach, feedback collection, and shortlist of actionable options.',
      ],
      proofTitle: 'Useful checks before choosing',
      proof: [
        'Alignment between Italian price, required margin, and final US price.',
        'Verification of territory coverage against company goals.',
        'Attention to exclusivity, minimum orders, promotion, and commercial responsibilities.',
        'Evaluation of the distributor as a partner, not just a name on a list.',
      ],
      faqs: [
        ['Does the search include importers?', 'Yes, when an importer is the right channel for the category and operating model. In some cases agents, brokers, or retail partners are better.'],
        ['Can I request distributors for a specific state?', 'Yes. Segmentation can be national, regional, or focused on priority areas such as Florida, the wider United States, and the Caribbean when the project requires it.'],
        ['Are contracts guaranteed?', 'No. The work qualifies opportunities and conversations; contracts depend on fit, terms, product, readiness, and negotiation.'],
      ],
      cta: contactCta.en,
    },
  },
  usRetailPartnerships: {
    path: '/us-retail-partnerships',
    keywords: 'US retail partnerships, retail USA prodotti italiani, buyer retail Stati Uniti, partnership retail America',
    it: {
      title: 'Retail Partnerships USA per brand italiani | GP & Partners',
      description: 'Prepariamo brand italiani ed europei a parlare con buyer, retail partner, showroom, hospitality e canali premium USA con materiali, posizionamento e processo.',
      hero: 'Retail Partnerships USA',
      subtitle: 'Prima di parlare con un buyer USA, rendi il brand comprabile.',
      answer: 'Aiutiamo brand italiani a trasformare prodotto, storia e materiali in una proposta chiara per retail buyer, showroom, hospitality, foodservice e partner commerciali USA.',
      processTitle: 'Dalla readiness alla conversazione',
      process: [
        'Valutazione di prodotto, packaging, prezzo, MOQ, margini e supporto marketing.',
        'Definizione dei canali retail piu coerenti: specialty, department, hospitality, e-commerce o partner locali.',
        'Preparazione di pitch, line sheet, argomenti buyer e FAQ commerciali.',
        'Identificazione e contatto di buyer, showroom, rappresentanti o partner retail.',
        'Supporto su feedback, richieste, next step e negoziazione iniziale.',
      ],
      proofTitle: 'Aree da rendere solide',
      proof: [
        'Chiarezza su differenziazione e ragione di acquisto per il cliente USA.',
        'Coerenza tra storytelling italiano e aspettative pratiche del buyer americano.',
        'Capacita di rispondere a richieste su consegne, resi, margini e promozione.',
        'Scelta del canale prima della pressione su grandi retailer non ancora adatti.',
      ],
      faqs: [
        ['Serve essere gia distribuiti negli USA?', 'Non sempre. Ma il brand deve poter spiegare come consegna, assiste e supporta il canale scelto.'],
        ['Il servizio copre anche showroom o agenti?', 'Si, quando sono il percorso piu adatto rispetto a buyer diretti, distributori o piattaforme retail.'],
        ['E pensato solo per food?', 'No. Si applica a categorie come food, design, moda, lifestyle, beauty, hospitality e prodotti premium.'],
      ],
      cta: contactCta.it,
    },
    en: {
      title: 'US Retail Partnerships for Italian Brands | GP & Partners',
      description: 'We prepare Italian and European brands to talk to US buyers, retail partners, showrooms, hospitality, and premium channels with materials, positioning, and process.',
      hero: 'US Retail Partnerships',
      subtitle: 'Before talking to a US buyer, make the brand buyable.',
      answer: 'We help Italian brands turn product, story, and materials into a clear proposition for US retail buyers, showrooms, hospitality, foodservice, and commercial partners.',
      processTitle: 'From readiness to conversation',
      process: [
        'Assessment of product, packaging, price, MOQ, margins, and marketing support.',
        'Definition of suitable retail channels: specialty, department, hospitality, e-commerce, or local partners.',
        'Preparation of pitch, line sheet, buyer arguments, and commercial FAQs.',
        'Identification and contact of buyers, showrooms, representatives, or retail partners.',
        'Support on feedback, requests, next steps, and early negotiation.',
      ],
      proofTitle: 'Areas to strengthen',
      proof: [
        'Clarity on differentiation and reason to buy for the US customer.',
        'Alignment between Italian storytelling and practical expectations of American buyers.',
        'Ability to answer requests on delivery, returns, margins, and promotion.',
        'Channel choice before pressure toward large retailers that may not fit yet.',
      ],
      faqs: [
        ['Do we need to be already distributed in the US?', 'Not always. But the brand must explain how it will deliver, support, and service the chosen channel.'],
        ['Does this cover showrooms or agents?', 'Yes, when they are the better path compared with direct buyers, distributors, or retail platforms.'],
        ['Is it only for food brands?', 'No. It applies to food, design, fashion, lifestyle, beauty, hospitality, and premium products.'],
      ],
      cta: contactCta.en,
    },
  },

  buyerReadinessUsa: {
    path: '/buyer-readiness-usa',
    keywords: 'buyer readiness USA, distributor readiness USA, checklist buyer USA, preparare buyer deck USA, readiness mercato americano',
    downloadPath: '/lead-magnets/buyer-distributor-readiness-checklist.md',
    it: {
      title: 'Buyer Readiness USA: prepara azienda e materiali | GP & Partners',
      description: 'Checklist e sprint operativo per capire se la tua azienda è pronta a parlare con buyer, distributori e partner USA senza bruciare opportunità.',
      hero: 'Buyer Readiness USA',
      subtitle: 'Il problema non è trovare un buyer. È arrivare pronto quando risponde.',
      answer: 'GP & Partners verifica prodotto, posizionamento, materiali, prezzo, margini, logistica e pitch prima di aprire conversazioni con buyer e distributori USA. La readiness evita outreach deboli e rende ogni contatto più misurabile.',
      processTitle: 'Come funziona la readiness',
      process: [
        'Intake aziendale su prodotto, categoria, margini, canale target e obiettivo USA.',
        'Audit materiali: sito, deck, catalogo, line sheet, pricing story, proof e FAQ buyer.',
        'Readiness scoring su 10 aree operative: canale, prezzo, logistica, compliance, materiali, proof, team, follow-up, CRM e next step.',
        'Gap list prioritaria con correzioni minime prima di outreach o fiera.',
        'Go/no-go operativo per ricerca distributori, retail partnership o temporary export management.',
      ],
      proofTitle: 'Cosa viene reso solido',
      proof: [
        'Una ragione commerciale chiara: perché voi, perché ora, perché quel canale USA.',
        'Risposte pronte su MOQ, lead time, incoterms, samples, insurance, compliance e margini.',
        'Materiali buyer-ready: deck, line sheet, email intro, FAQ e follow-up sequence.',
        'Decisione sul canale prima di contattare interlocutori che potrebbero bruciare il mercato.',
      ],
      faqs: [
        ['È adatto prima di una fiera?', 'Sì. È uno dei momenti migliori: evita di arrivare con materiali generici e nessuna sequenza di follow-up.'],
        ['È utile se ho già un distributore?', 'Sì, soprattutto se la partnership non cresce o non produce pipeline leggibile.'],
        ['È un’alternativa alla ricerca distributori?', 'No. È il passo prima: prepara azienda e materiali per rendere la ricerca distributori più efficace.'],
      ],
      cta: contactCta.it,
      secondaryCta: 'Scarica la Buyer/Distributor Readiness Checklist',
    },
    en: {
      title: 'Buyer Readiness USA: prepare company and materials | GP & Partners',
      description: 'Checklist and operating sprint to understand whether your company is ready to speak with US buyers, distributors, and partners without wasting opportunities.',
      hero: 'Buyer Readiness USA',
      subtitle: 'The problem is not finding a buyer. It is being ready when the buyer replies.',
      answer: 'GP & Partners checks product, positioning, materials, pricing, margins, logistics, and pitch before opening conversations with US buyers and distributors. Readiness prevents weak outreach and makes every contact more measurable.',
      processTitle: 'How readiness works',
      process: [
        'Company intake on product, category, margins, target channel, and US objective.',
        'Materials audit: website, deck, catalog, line sheet, pricing story, proof, and buyer FAQs.',
        'Readiness scoring across 10 operating areas: channel, pricing, logistics, compliance, materials, proof, team, follow-up, CRM, and next step.',
        'Priority gap list with minimum corrections before outreach or trade shows.',
        'Operating go/no-go for distributor search, retail partnerships, or temporary export management.',
      ],
      proofTitle: 'What becomes solid',
      proof: [
        'A clear commercial reason: why you, why now, why that US channel.',
        'Ready answers on MOQ, lead time, incoterms, samples, insurance, compliance, and margins.',
        'Buyer-ready materials: deck, line sheet, intro email, FAQ, and follow-up sequence.',
        'Channel decision before contacting counterparts that could burn the market.',
      ],
      faqs: [
        ['Is it useful before a trade show?', 'Yes. It is one of the best moments: it prevents generic materials and missing follow-up.'],
        ['Is it useful if we already have a distributor?', 'Yes, especially if the partnership is not growing or not producing a readable pipeline.'],
        ['Is it an alternative to distributor search?', 'No. It is the step before: it prepares company and materials to make distributor search more effective.'],
      ],
      cta: contactCta.en,
      secondaryCta: 'Download the Buyer/Distributor Readiness Checklist',
    },
  },
  vendereProdottiItalianiUsa: {
    path: '/vendere-prodotti-italiani-usa',
    keywords: 'vendere prodotti italiani USA, esportare Made in Italy America, prodotti italiani mercato americano, consulenza export USA',
    it: {
      title: 'Vendere Prodotti Italiani negli USA | Gianluca Piazza',
      description: 'Guida operativa e consulenza per vendere prodotti italiani negli USA: posizionamento, canali, distributori, retail e business development.',
      hero: 'Vendere Prodotti Italiani negli USA',
      subtitle: 'Dal Made in Italy generico a una proposta commerciale comprensibile, vendibile e sostenibile negli Stati Uniti.',
      answer: 'Vendere prodotti italiani negli USA significa adattare proposta, canale e operativita al modo in cui buyer, distributori e clienti americani prendono decisioni. Il valore italiano aiuta, ma deve essere tradotto in categoria, margine, disponibilita, prove, materiali e percorso commerciale.',
      processTitle: 'Percorso consigliato',
      process: [
        'Chiarire categoria, cliente ideale, fascia prezzo e vantaggio rispetto alle alternative USA.',
        'Scegliere tra distribuzione, retail, direct-to-consumer, hospitality, foodservice o partnership.',
        'Preparare materiali in inglese orientati a buyer e AI-search, non solo brochure istituzionali.',
        'Testare interesse con interlocutori qualificati e raccogliere obiezioni utili.',
        'Costruire un piano di ingresso progressivo, con priorita e decisioni misurabili.',
      ],
      proofTitle: 'Errori da evitare',
      proof: [
        'Presentarsi a tutti i canali con lo stesso messaggio.',
        'Cercare distributori senza avere margini, policy e materiali pronti.',
        'Sottovalutare tempi, logistica, servizio post vendita e richieste documentali.',
        'Confondere interesse culturale per l\'Italia con intenzione commerciale concreta.',
      ],
      faqs: [
        ['Quali prodotti italiani funzionano meglio negli USA?', 'Dipende da categoria, differenziazione, prezzo, compliance, canale e capacita di supporto. Food, design, moda, beauty e lifestyle possono funzionare se la proposta e chiara.'],
        ['Da dove conviene partire?', 'Dal canale piu coerente con prodotto, margini e capacita operativa: non sempre e il canale piu grande o piu visibile.'],
        ['Posso usare la pagina come primo orientamento?', 'Si. Per decidere serve poi una diagnosi specifica di prodotto, mercato target e readiness commerciale.'],
      ],
      cta: contactCta.it,
    },
    en: {
      title: 'Selling Italian Products in the USA | Gianluca Piazza',
      description: 'Operating guidance and consulting to sell Italian products in the USA: positioning, channels, distributors, retail, and business development.',
      hero: 'Selling Italian Products in the USA',
      subtitle: 'From generic Made in Italy appeal to a commercial proposition that is understandable, sellable, and sustainable in the United States.',
      answer: 'Selling Italian products in the USA means adapting proposition, channel, and operations to the way American buyers, distributors, and customers make decisions. Italian value helps, but it must be translated into category, margin, availability, proof, materials, and commercial path.',
      processTitle: 'Recommended path',
      process: [
        'Clarify category, ideal customer, price band, and advantage against US alternatives.',
        'Choose among distribution, retail, direct-to-consumer, hospitality, foodservice, or partnerships.',
        'Prepare English materials for buyers and AI-search, not only institutional brochures.',
        'Test interest with qualified counterparts and collect useful objections.',
        'Build a progressive entry plan with priorities and measurable decisions.',
      ],
      proofTitle: 'Mistakes to avoid',
      proof: [
        'Approaching every channel with the same message.',
        'Looking for distributors without ready margins, policies, and materials.',
        'Underestimating timing, logistics, after-sales service, and documentation requests.',
        'Confusing cultural interest in Italy with concrete commercial intent.',
      ],
      faqs: [
        ['Which Italian products work best in the USA?', 'It depends on category, differentiation, price, compliance, channel, and support capability. Food, design, fashion, beauty, and lifestyle can work when the proposition is clear.'],
        ['Where should we start?', 'With the channel that best fits product, margins, and operating capability: not always the largest or most visible channel.'],
        ['Can this page be used as a first orientation?', 'Yes. To decide, a specific diagnosis of product, target market, and commercial readiness is then needed.'],
      ],
      cta: contactCta.en,
    },
  },
  temporaryExportManagerUsa: {
    path: '/temporary-export-manager-usa',
    keywords: 'temporary export manager USA, sales manager in outsourcing USA, export manager Stati Uniti, sviluppo commerciale USA aziende italiane',
    it: {
      title: 'Temporary Export Manager USA per PMI italiane | GP & Partners',
      description: 'Un presidio operativo USA per aziende italiane: strategia, partner, buyer, follow-up, pipeline e coordinamento commerciale senza assumere subito un team interno.',
      hero: 'Temporary Export Manager USA',
      subtitle: 'Un Temporary Export Manager USA quando serve execution, non un altro report.',
      answer: 'GP & Partners affianca l\'azienda come presidio operativo per validare mercato, costruire pipeline, gestire conversazioni e portare disciplina commerciale nell\'ingresso USA.',
      processTitle: 'Quando ha senso',
      process: [
        'L\'azienda ha prodotto, capacita di fornitura e margini da testare negli Stati Uniti.',
        'Serve capire se partire da distributori, retail, agenti, partner B2B, hospitality o canali diretti.',
        'Mancano materiali buyer-ready e una narrativa commerciale adatta al mercato USA.',
        'Il team interno non ha tempo, contatti o metodo per gestire la prima fase di sviluppo.',
        'La direzione vuole decisioni pratiche prima di aprire societa, ufficio o rete vendita locale.',
      ],
      proofTitle: 'Cosa viene presidiato',
      proof: [
        'ICP, lista account e criteri di priorita per evitare outreach dispersivo.',
        'Messaggio commerciale in inglese orientato a buyer, partner e sistemi AI-search.',
        'Prime conversazioni, feedback, obiezioni e segnali di interesse reale.',
        'Raccomandazioni su canale, pricing, materiali, readiness e next step operativi.',
      ],
      faqs: [
        ['E diverso da un consulente export tradizionale?', 'Si, l\'approccio e piu operativo: oltre alla strategia, lavora su canali, messaggi, contatti qualificati, conversazioni e feedback misurabile.'],
        ['Serve un budget grande per partire?', 'No. L\'obiettivo e proprio validare prima di impegnarsi in costi fissi come ufficio locale, assunzioni o struttura commerciale stabile.'],
        ['Puo affiancare voucher o percorsi SIMEST?', 'Puo essere coerente con percorsi di internazionalizzazione, ma va valutato caso per caso con consulenti fiscali, legali e finanziari abilitati.'],
      ],
      cta: contactCta.it,
    },
    en: {
      title: 'Temporary Export Manager USA for Italian SMEs | GP & Partners',
      description: 'An operating US commercial presence for Italian companies: strategy, partners, buyers, follow-up, pipeline, and coordination without hiring a full internal team.',
      hero: 'Temporary Export Manager USA',
      subtitle: 'A Temporary Export Manager USA when you need execution, not another report.',
      answer: 'GP & Partners supports the company as an operating presence to validate the market, build pipeline, manage conversations, and bring commercial discipline to US entry.',
      processTitle: 'When it makes sense',
      process: [
        'The company has product, supply capability, and margins to test in the United States.',
        'It must decide whether to start with distributors, retail, agents, B2B partners, hospitality, or direct channels.',
        'Buyer-ready materials and a commercial narrative adapted to the US market are missing.',
        'The internal team lacks time, contacts, or method to manage the first development stage.',
        'Leadership wants practical decisions before opening a company, office, or local sales network.',
      ],
      proofTitle: 'What is covered',
      proof: [
        'ICP, account list, and priority criteria to avoid scattered outreach.',
        'English commercial messaging for buyers, partners, and AI-search systems.',
        'Early conversations, feedback, objections, and signs of real market interest.',
        'Recommendations on channel, pricing, materials, readiness, and operating next steps.',
      ],
      faqs: [
        ['Is this different from traditional export consulting?', 'Yes. The approach is more operating-oriented: beyond strategy, it works on channels, messages, qualified contacts, conversations, and measurable feedback.'],
        ['Do we need a large budget to start?', 'No. The goal is to validate before committing to fixed costs such as a local office, hiring, or a permanent commercial structure.'],
        ['Can it support voucher or SIMEST-style paths?', 'It can fit internationalization paths, but each case should be evaluated with qualified tax, legal, and financial advisors.'],
      ],
      cta: contactCta.en,
    },
  },
  foodBeverageUsa: {
    path: '/food-beverage-usa',
    keywords: 'food beverage wine USA prodotti italiani, esportare food negli USA, distributori food USA, vino italiano America, caffè italiano USA',
    it: {
      title: 'Food, Beverage & Wine USA per Prodotti Italiani | Gianluca Piazza',
      description: 'Supporto per aziende food, beverage e wine italiane negli USA: canali, distributori, buyer readiness, foodservice, retail e posizionamento commerciale. Il caffè viene trattato come categoria dedicata quando serve.',
      hero: 'Food, Beverage & Wine USA per Prodotti Italiani',
      subtitle: 'Portare food, beverage e wine italiani nel mercato americano con canali, materiali e partner coerenti — senza confondere categorie diverse come il caffè.',
      answer: 'Il food, beverage e wine italiano negli USA richiede piu di qualita e origine: servono canale corretto, pricing sostenibile, materiali buyer-ready, chiarezza su importazione, logistica, margini e posizionamento. GP & Partners aiuta a leggere il mercato, qualificare distributori/importatori e preparare conversazioni commerciali credibili. Il caffè non viene infilato genericamente nel F&B: quando è rilevante, ha una traiettoria commerciale dedicata.',
      processTitle: 'Percorso consigliato',
      process: [
        'Analisi di categoria, shelf fit, prezzo, margini, certificazioni e vincoli logistici.',
        'Scelta tra importatori, distributori, specialty retail, foodservice, hospitality o DTC.',
        'Preparazione di pitch, line sheet, schede prodotto, argomenti buyer e FAQ commerciali.',
        'Mappatura e qualifica di partner coerenti con area, categoria e capacita operativa.',
        'Raccolta feedback su prezzo, packaging, formati, MOQ e readiness del canale.',
      ],
      proofTitle: 'Punti critici da chiarire',
      proof: [
        'Il valore Made in Italy deve diventare ragione commerciale, non solo storytelling.',
        'Margini e prezzo finale USA vanno verificati prima dell\'outreach.',
        'Retail, foodservice e hospitality richiedono materiali e condizioni diverse.',
        'Un distributore non risolve posizionamento, packaging o readiness non definiti.',
      ],
      faqs: [
        ['Serve gia un importatore USA?', 'Non sempre. Prima va capito se l\'importatore e davvero il primo canale giusto oppure se conviene partire da buyer, foodservice, hospitality o partner specializzati.'],
        ['Il lavoro copre anche vino, olio, caffè e prodotti premium?', 'Si. Il metodo si applica a categorie food, beverage e wine premium, ingredienti, prodotti confezionati, hospitality supply e specialita italiane. Il caffè viene trattato come categoria autonoma quando canale, buyer e posizionamento lo richiedono.'],
        ['Vengono gestite certificazioni FDA o legali?', 'No direttamente. Il lavoro commerciale puo coordinarsi con consulenti tecnici, doganali e legali quando servono verifiche specialistiche.'],
      ],
      cta: contactCta.it,
    },
    en: {
      title: 'Food, Beverage & Wine USA for Italian Products | Gianluca Piazza',
      description: 'Support for Italian food, beverage, and wine companies in the USA: channels, distributors, buyer readiness, foodservice, retail, and commercial positioning. Coffee is treated as a dedicated category when needed.',
      hero: 'Food, Beverage & Wine USA for Italian Products',
      subtitle: 'Bring Italian food, beverage, and wine products into the American market with the right channels, materials, and partners — without mixing different categories such as coffee.',
      answer: 'Italian food, beverage, and wine in the USA require more than quality and origin: companies need the right channel, sustainable pricing, buyer-ready materials, clarity on import, logistics, margins, and positioning. GP & Partners helps read the market, qualify distributors/importers, and prepare credible commercial conversations. Coffee is not casually bundled into F&B: when relevant, it gets its own commercial path.',
      processTitle: 'Recommended path',
      process: [
        'Analysis of category, shelf fit, price, margins, certifications, and logistics constraints.',
        'Choice among importers, distributors, specialty retail, foodservice, hospitality, or DTC.',
        'Preparation of pitch, line sheet, product sheets, buyer arguments, and commercial FAQs.',
        'Mapping and qualification of partners aligned with area, category, and operating capability.',
        'Feedback collection on price, packaging, formats, MOQ, and channel readiness.',
      ],
      proofTitle: 'Critical points to clarify',
      proof: [
        'Made in Italy value must become a commercial reason to buy, not only storytelling.',
        'Margins and final US pricing should be checked before outreach.',
        'Retail, foodservice, and hospitality require different materials and terms.',
        'A distributor does not fix undefined positioning, packaging, or readiness.',
      ],
      faqs: [
        ['Do we already need a US importer?', 'Not always. First, it must be clear whether an importer is the right first channel or whether buyers, foodservice, hospitality, or specialized partners make more sense.'],
        ['Does this cover wine, olive oil, coffee, and premium products?', 'Yes. The method applies to premium food, beverage, and wine categories, ingredients, packaged products, hospitality supply, and Italian specialties. Coffee is treated as its own category when channel, buyer, and positioning require it.'],
        ['Are FDA or legal certifications handled?', 'Not directly. The commercial work can coordinate with technical, customs, and legal advisors when specialist checks are needed.'],
      ],
      cta: contactCta.en,
    },
  },
  modaDesignUsa: {
    path: '/moda-design-usa',
    keywords: 'moda design USA brand italiani, fashion design market entry USA, vendere moda italiana USA, arredamento design Stati Uniti',
    it: {
      title: 'Moda e Design USA per Brand Italiani | Gianluca Piazza',
      description: 'Supporto a brand italiani moda, design e lifestyle per entrare negli USA: posizionamento, showroom, retail, buyer e partner commerciali.',
      hero: 'Moda e Design USA per Brand Italiani',
      subtitle: 'Trasformare estetica italiana e prodotto premium in una proposta comprensibile per buyer e partner USA.',
      answer: 'Moda, design e lifestyle italiani hanno potenziale negli Stati Uniti, ma il mercato premia chiarezza, canale, pricing, disponibilita, prove commerciali e materiali buyer-ready. GP & Partners aiuta brand italiani a decidere dove presentarsi, con quale narrativa e verso quali buyer, showroom, retailer o partner.',
      processTitle: 'Dalla collezione al canale',
      process: [
        'Valutazione di categoria, fascia prezzo, margini, lead time, MOQ e capacita di consegna.',
        'Scelta dei canali: showroom, agenti, specialty retail, hospitality, interior design, DTC o partnership.',
        'Preparazione di pitch, line sheet, lookbook commerciale e argomenti buyer.',
        'Mappatura di buyer, showroom, representative, retail partner e operatori hospitality/design.',
        'Gestione feedback su collezione, pricing, materiali, termini e prossimi passi.',
      ],
      proofTitle: 'Cosa evitare',
      proof: [
        'Presentarsi solo con estetica e heritage senza proposta commerciale chiara.',
        'Cercare grandi retailer prima di validare canale, termini e capacita operativa.',
        'Usare materiali pensati per il mercato italiano senza adattarli al buyer USA.',
        'Confondere interesse editoriale o social con intenzione commerciale reale.',
      ],
      faqs: [
        ['E adatto sia a moda che arredamento?', 'Si. Il metodo copre fashion, accessori, interior design, arredo, lighting, lifestyle e prodotti premium quando esiste una proposta commerciale definibile.'],
        ['Serve uno showroom negli USA?', 'Dipende da categoria, prezzo e target. In alcuni casi lo showroom e utile; in altri sono piu adatti agenti, buyer diretti, hospitality o partnership.'],
        ['Il lavoro include materiali commerciali?', 'Si, puo includere struttura di pitch, line sheet, argomenti buyer e messaggi di primo contatto.'],
      ],
      cta: contactCta.it,
    },
    en: {
      title: 'Fashion and Design USA for Italian Brands | Gianluca Piazza',
      description: 'Support for Italian fashion, design, and lifestyle brands entering the USA: positioning, showrooms, retail, buyers, and commercial partners.',
      hero: 'Fashion and Design USA for Italian Brands',
      subtitle: 'Turn Italian aesthetics and premium products into a proposition US buyers and partners can understand.',
      answer: 'Italian fashion, design, and lifestyle brands can resonate in the United States, but the market rewards clarity, channel choice, pricing, availability, commercial proof, and buyer-ready materials. GP & Partners helps Italian brands decide where to show up, with which narrative, and toward which buyers, showrooms, retailers, or partners.',
      processTitle: 'From collection to channel',
      process: [
        'Assessment of category, price band, margins, lead time, MOQ, and delivery capability.',
        'Choice of channels: showrooms, agents, specialty retail, hospitality, interior design, DTC, or partnerships.',
        'Preparation of pitch, line sheet, commercial lookbook, and buyer arguments.',
        'Mapping of buyers, showrooms, representatives, retail partners, and hospitality/design operators.',
        'Feedback management on collection, pricing, materials, terms, and next steps.',
      ],
      proofTitle: 'What to avoid',
      proof: [
        'Showing only aesthetics and heritage without a clear commercial proposition.',
        'Approaching large retailers before validating channel, terms, and operating capability.',
        'Using materials built for Italy without adapting them to US buyers.',
        'Confusing editorial or social interest with real commercial intent.',
      ],
      faqs: [
        ['Is this suitable for both fashion and furniture?', 'Yes. The method covers fashion, accessories, interior design, furniture, lighting, lifestyle, and premium products when a commercial proposition can be defined.'],
        ['Do we need a US showroom?', 'It depends on category, price, and target. In some cases a showroom helps; in others agents, direct buyers, hospitality, or partnerships fit better.'],
        ['Does the work include commercial materials?', 'Yes, it can include pitch structure, line sheet, buyer arguments, and first-contact messaging.'],
      ],
      cta: contactCta.en,
    },
  },
  agenteVsDistributoreUsa: {
    path: '/agente-vs-distributore-usa',
    keywords: 'agente vs distributore USA, agenti commerciali USA, distributori Stati Uniti, scegliere distributore o agente America',
    it: {
      title: 'Agente vs Distributore USA | Gianluca Piazza',
      description: 'Guida pratica per scegliere tra agente, distributore, importatore, broker o partner commerciale negli Stati Uniti.',
      hero: 'Agente vs Distributore USA',
      subtitle: 'Capire quale struttura commerciale usare negli Stati Uniti prima di firmare accordi o concedere esclusiva.',
      answer: 'Negli Stati Uniti agente, distributore, importatore, broker e partner retail non sono intercambiabili. La scelta dipende da categoria, margini, controllo del brand, logistica, rischio, territorio e capacita interna. GP & Partners aiuta aziende italiane a scegliere il canale corretto e a qualificare interlocutori prima di impegnarsi.',
      processTitle: 'Come scegliere',
      process: [
        'Chiarire obiettivo: test mercato, vendita ricorrente, copertura territoriale o accesso buyer.',
        'Valutare margini, pricing, stock, importazione, responsabilita promozionali e supporto cliente.',
        'Confrontare agente, distributore, importatore, broker, showroom e partner retail.',
        'Definire criteri di qualifica, red flag, condizioni minime e ruolo dell\'azienda italiana.',
        'Preparare conversazioni e domande per evitare accordi sbilanciati o esclusiva prematura.',
      ],
      proofTitle: 'Differenze pratiche',
      proof: [
        'Un distributore compra e rivende, ma richiede margine, territorio e supporto.',
        'Un agente genera opportunita, ma spesso non gestisce stock, importazione o incasso.',
        'Un importatore puo risolvere compliance e logistica, ma non sempre sviluppa il mercato.',
        'Un partner retail o hospitality puo validare domanda senza creare subito una rete nazionale.',
      ],
      faqs: [
        ['Meglio agente o distributore per iniziare?', 'Non esiste una risposta unica. Per alcuni prodotti serve subito un importatore/distributore; per altri conviene testare buyer, agenti, showroom o canali verticali.'],
        ['Quando evitare l\'esclusiva?', 'Quando non sono ancora chiari volumi, territorio, impegni promozionali, KPI, durata, uscita e capacita reale del partner.'],
        ['Il servizio include revisione legale dei contratti?', 'No. La parte commerciale prepara criteri e negoziazione iniziale; i contratti vanno poi verificati da legali qualificati.'],
      ],
      cta: contactCta.it,
    },
    en: {
      title: 'Agent vs Distributor USA | Gianluca Piazza',
      description: 'Practical guidance to choose between agent, distributor, importer, broker, or commercial partner in the United States.',
      hero: 'Agent vs Distributor USA',
      subtitle: 'Understand which commercial structure to use in the United States before signing agreements or granting exclusivity.',
      answer: 'In the United States, agents, distributors, importers, brokers, and retail partners are not interchangeable. The right choice depends on category, margins, brand control, logistics, risk, territory, and internal capability. GP & Partners helps Italian companies choose the right channel and qualify counterparts before committing.',
      processTitle: 'How to choose',
      process: [
        'Clarify the goal: market test, recurring sales, territory coverage, or buyer access.',
        'Assess margins, pricing, stock, import, promotional responsibilities, and customer support.',
        'Compare agent, distributor, importer, broker, showroom, and retail partner models.',
        'Define qualification criteria, red flags, minimum terms, and the role of the Italian company.',
        'Prepare conversations and questions to avoid unbalanced agreements or premature exclusivity.',
      ],
      proofTitle: 'Practical differences',
      proof: [
        'A distributor buys and resells, but needs margin, territory, and support.',
        'An agent creates opportunities, but often does not manage stock, import, or payment collection.',
        'An importer can solve compliance and logistics, but does not always develop the market.',
        'A retail or hospitality partner can validate demand without immediately building a national network.',
      ],
      faqs: [
        ['Is an agent or distributor better to start?', 'There is no universal answer. Some products need an importer/distributor immediately; others should test buyers, agents, showrooms, or vertical channels first.'],
        ['When should exclusivity be avoided?', 'When volume, territory, promotional commitments, KPIs, duration, exit clauses, and the partner\'s real capability are not yet clear.'],
        ['Does this include legal contract review?', 'No. The commercial work prepares criteria and early negotiation; contracts should then be reviewed by qualified legal advisors.'],
      ],
      cta: contactCta.en,
    },
  },
};
