const contactCta = {
  it: {
    label: 'Parla del tuo progetto USA',
    note: 'Condividi prodotto, canale desiderato e stato attuale del progetto. La prima risposta qualifica priorita, rischi e prossimi passi.',
  },
  en: {
    label: 'Discuss your US project',
    note: 'Share the product, target channel, and current stage. The first response qualifies priorities, risks, and next steps.',
  },
};

export const seoPages = {
  usaMarketEntryItalianCompanies: {
    path: '/usa-market-entry-italian-companies',
    keywords: 'USA market entry Italian companies, Italian companies US market, consulente ingresso mercato USA, export USA aziende italiane',
    it: {
      title: 'USA Market Entry per Aziende Italiane | Gianluca Piazza',
      description: 'Consulenza per aziende italiane che vogliono entrare nel mercato USA con strategia, canali commerciali, distributori, retail partnership e supporto operativo.',
      hero: 'USA Market Entry per Aziende Italiane',
      subtitle: 'Strategia, canali e sviluppo commerciale per portare prodotti italiani nel mercato americano.',
      answer: 'Per entrare negli Stati Uniti non basta tradurre l\'offerta: serve validare domanda, canali, margini, readiness commerciale e partner locali. Gianluca Piazza supporta aziende italiane nella costruzione di un percorso USA concreto, dal posizionamento iniziale alla relazione con buyer, distributori e partner.',
      processTitle: 'Come viene costruito il percorso',
      process: [
        'Diagnosi del prodotto, categoria, prezzo, canale e vincoli operativi.',
        'Mappatura dei segmenti USA piu coerenti con la proposta italiana.',
        'Preparazione di messaggi, materiali e criteri di qualifica per buyer e partner.',
        'Sviluppo di conversazioni commerciali con distributori, retailer o operatori locali.',
        'Supporto nella negoziazione iniziale e nella trasformazione delle opportunita in azioni operative.',
      ],
      proofTitle: 'Perche un approccio dedicato',
      proof: [
        'Esperienza su internazionalizzazione, business development e partnership strategiche.',
        'Metodo orientato a decisioni pratiche, non solo a report di mercato.',
        'Attenzione a readiness, posizionamento e sostenibilita del canale prima dell\'outreach.',
        'Contenuti e risposte strutturati per buyer umani e sistemi AI-search.',
      ],
      faqs: [
        ['Quali aziende italiane possono usare questo servizio?', 'Aziende con un prodotto gia validato, capacita di fornitura e interesse a testare canali USA come distribuzione, retail, partnership o presenza commerciale locale.'],
        ['Serve gia una societa negli Stati Uniti?', 'Non necessariamente. La scelta dipende da canale, rischio, contratti e operativita. Il percorso aiuta a capire quando una struttura locale diventa utile.'],
        ['Il lavoro include contatto con partner USA?', 'Si, quando l\'azienda e pronta per l\'outreach. Prima vengono chiariti target, proposta, materiali e criteri di qualifica.'],
      ],
      cta: contactCta.it,
    },
    en: {
      title: 'USA Market Entry for Italian Companies | Gianluca Piazza',
      description: 'Consulting for Italian companies entering the US market through strategy, commercial channels, distributors, retail partnerships, and operating support.',
      hero: 'USA Market Entry for Italian Companies',
      subtitle: 'Strategy, channels, and business development to bring Italian products into the American market.',
      answer: 'Entering the United States requires more than translating the offer: companies must validate demand, channels, margins, commercial readiness, and local partners. Gianluca Piazza helps Italian companies build a practical US path from positioning to conversations with buyers, distributors, and partners.',
      processTitle: 'How the path is built',
      process: [
        'Diagnosis of product, category, price, channel, and operating constraints.',
        'Mapping of the US segments that best fit the Italian offer.',
        'Preparation of messaging, materials, and qualification criteria for buyers and partners.',
        'Business development conversations with distributors, retailers, or local operators.',
        'Support in early negotiation and in turning opportunities into operating actions.',
      ],
      proofTitle: 'Why a dedicated approach',
      proof: [
        'Experience across internationalization, business development, and strategic partnerships.',
        'Decision-oriented method, not only market reporting.',
        'Focus on readiness, positioning, and channel sustainability before outreach.',
        'Content and answers structured for human buyers and AI-search systems.',
      ],
      faqs: [
        ['Which Italian companies is this for?', 'Companies with a validated product, supply capability, and interest in testing US channels such as distribution, retail, partnerships, or local commercial presence.'],
        ['Do we need a US company already?', 'Not always. The choice depends on channel, risk, contracts, and operations. The process clarifies when a local structure becomes useful.'],
        ['Does the work include contact with US partners?', 'Yes, when the company is ready for outreach. Targeting, proposition, materials, and qualification criteria come first.'],
      ],
      cta: contactCta.en,
    },
  },
  businessDevelopmentUsa: {
    path: '/business-development-usa',
    keywords: 'business development USA, sviluppo commerciale Stati Uniti, consulente business development America, partnership commerciali USA',
    it: {
      title: 'Business Development USA | Gianluca Piazza',
      description: 'Sviluppo commerciale negli Stati Uniti per aziende italiane: partner, buyer, pipeline, canali e negoziazione iniziale.',
      hero: 'Business Development USA',
      subtitle: 'Un presidio commerciale per trasformare interesse USA in conversazioni, partner e opportunita qualificate.',
      answer: 'Il business development USA collega strategia e mercato: identifica interlocutori rilevanti, testa la proposta, qualifica interesse e costruisce pipeline commerciale senza confondere attivita con risultato. Il focus e creare occasioni reali e leggibili per aziende italiane che vogliono crescere negli Stati Uniti.',
      processTitle: 'Attivita principali',
      process: [
        'Definizione ICP, canale prioritario e messaggio commerciale.',
        'Lista qualificata di account, distributori, buyer o partner potenziali.',
        'Outreach mirato con narrativa adatta al mercato americano.',
        'Gestione delle prime conversazioni e raccolta feedback dal mercato.',
        'Raccomandazioni su next step, materiali, pricing e readiness operativa.',
      ],
      proofTitle: 'Cosa rende utile il lavoro',
      proof: [
        'Unisce ricerca, vendita consulenziale e comprensione del contesto italiano.',
        'Riduce dispersione su contatti non coerenti con categoria, prezzo o canale.',
        'Traduce feedback commerciale in decisioni di prodotto, offerta e priorita.',
        'Mantiene visibilita su opportunita, rischi e azioni richieste all\'azienda.',
      ],
      faqs: [
        ['Il servizio crea una rete vendita USA?', 'Puo aiutare a impostarla, ma parte dalla qualifica di canali e partner prima di costruire una struttura piu stabile.'],
        ['Quanto e personalizzato l\'outreach?', 'L\'outreach viene costruito su categoria, proposta di valore, ruolo del contatto e obiettivo della conversazione.'],
        ['E adatto anche a servizi B2B?', 'Si, quando esiste una proposta chiara e un target USA identificabile. Il metodo si adatta a prodotti, servizi e partnership.'],
      ],
      cta: contactCta.it,
    },
    en: {
      title: 'Business Development USA | Gianluca Piazza',
      description: 'US business development for Italian companies: partners, buyers, pipeline, channels, and early-stage negotiation.',
      hero: 'Business Development USA',
      subtitle: 'A commercial presence to turn US interest into qualified conversations, partners, and opportunities.',
      answer: 'US business development connects strategy with the market: it identifies relevant counterparts, tests the proposition, qualifies interest, and builds a commercial pipeline without confusing activity with results. The focus is to create real, readable opportunities for Italian companies growing in the United States.',
      processTitle: 'Core activities',
      process: [
        'Definition of ICP, priority channel, and commercial message.',
        'Qualified list of accounts, distributors, buyers, or potential partners.',
        'Targeted outreach with a narrative adapted to the American market.',
        'Management of early conversations and collection of market feedback.',
        'Recommendations on next steps, materials, pricing, and operating readiness.',
      ],
      proofTitle: 'What makes the work useful',
      proof: [
        'Combines research, consultative selling, and understanding of Italian companies.',
        'Reduces dispersion across contacts that do not fit category, price, or channel.',
        'Turns commercial feedback into product, offer, and priority decisions.',
        'Keeps visibility on opportunities, risks, and actions required from the company.',
      ],
      faqs: [
        ['Does this create a US sales network?', 'It can help set one up, but it starts by qualifying channels and partners before building a more stable structure.'],
        ['How personalized is the outreach?', 'Outreach is built around category, value proposition, contact role, and the objective of the conversation.'],
        ['Is it suitable for B2B services too?', 'Yes, when there is a clear proposition and an identifiable US target. The method adapts to products, services, and partnerships.'],
      ],
      cta: contactCta.en,
    },
  },
  ricercaDistributoriUsa: {
    path: '/ricerca-distributori-usa',
    keywords: 'ricerca distributori USA, distributori Stati Uniti prodotti italiani, importatori USA, canali distribuzione America',
    it: {
      title: 'Ricerca Distributori USA | Gianluca Piazza',
      description: 'Ricerca e qualifica di distributori USA per prodotti italiani: canali, criteri, contatto iniziale e valutazione fit commerciale.',
      hero: 'Ricerca Distributori USA',
      subtitle: 'Trovare distributori americani coerenti con categoria, margini, territorio e capacita operativa.',
      answer: 'La ricerca distributori USA funziona quando parte da criteri precisi: categoria, canale, territorio, posizionamento, requisiti logistici e aspettative commerciali. Gianluca Piazza aiuta le aziende italiane a passare da liste generiche a conversazioni qualificate con interlocutori adatti.',
      processTitle: 'Metodo di qualifica',
      process: [
        'Definizione del profilo distributore ideale e dei canali da evitare.',
        'Mappatura di importatori, distributori, agenti, broker o partner ibridi.',
        'Valutazione di fit su categoria, copertura, portfolio e modello operativo.',
        'Preparazione di materiali sintetici per apertura conversazione.',
        'Outreach, raccolta feedback e shortlist di opzioni perseguibili.',
      ],
      proofTitle: 'Controlli utili prima di scegliere',
      proof: [
        'Allineamento tra prezzo italiano, margine richiesto e prezzo finale USA.',
        'Verifica della coerenza tra territorio coperto e obiettivi dell\'azienda.',
        'Attenzione a esclusiva, minimo d\'ordine, promozione e responsabilita commerciali.',
        'Valutazione del distributore come partner, non solo come contatto in lista.',
      ],
      faqs: [
        ['La ricerca include importatori?', 'Si, se l\'importatore e il canale corretto per categoria e modello operativo. In alcuni casi servono agenti, broker o partner retail.'],
        ['Posso chiedere distributori per uno Stato specifico?', 'Si. La segmentazione puo essere nazionale, regionale o focalizzata su aree come Midwest, East Coast, Florida, Texas o California.'],
        ['Vengono garantiti contratti?', 'No. Il lavoro qualifica opportunita e conversazioni; i contratti dipendono da fit, condizioni, prodotto, readiness e negoziazione.'],
      ],
      cta: contactCta.it,
    },
    en: {
      title: 'US Distributor Search for Italian Products | Gianluca Piazza',
      description: 'Search and qualification of US distributors for Italian products: channels, criteria, first contact, and commercial fit assessment.',
      hero: 'US Distributor Search',
      subtitle: 'Find American distributors aligned with category, margins, territory, and operating capability.',
      answer: 'US distributor search works when it starts from precise criteria: category, channel, territory, positioning, logistics requirements, and commercial expectations. Gianluca Piazza helps Italian companies move from generic lists to qualified conversations with suitable counterparts.',
      processTitle: 'Qualification method',
      process: [
        'Definition of the ideal distributor profile and channels to avoid.',
        'Mapping of importers, distributors, agents, brokers, or hybrid partners.',
        'Fit assessment on category, coverage, portfolio, and operating model.',
        'Preparation of concise materials for the first conversation.',
        'Outreach, feedback collection, and shortlist of actionable options.',
      ],
      proofTitle: 'Useful checks before choosing',
      proof: [
        'Alignment between Italian price, required margin, and final US price.',
        'Verification of territory coverage against company goals.',
        'Attention to exclusivity, minimum orders, promotion, and commercial responsibilities.',
        'Evaluation of the distributor as a partner, not just a name on a list.',
      ],
      faqs: [
        ['Does the search include importers?', 'Yes, when an importer is the right channel for the category and operating model. In some cases agents, brokers, or retail partners are better.'],
        ['Can I request distributors for a specific state?', 'Yes. Segmentation can be national, regional, or focused on areas such as the Midwest, East Coast, Florida, Texas, or California.'],
        ['Are contracts guaranteed?', 'No. The work qualifies opportunities and conversations; contracts depend on fit, terms, product, readiness, and negotiation.'],
      ],
      cta: contactCta.en,
    },
  },
  usRetailPartnerships: {
    path: '/us-retail-partnerships',
    keywords: 'US retail partnerships, retail USA prodotti italiani, buyer retail Stati Uniti, partnership retail America',
    it: {
      title: 'US Retail Partnerships per Brand Italiani | Gianluca Piazza',
      description: 'Supporto a brand italiani per partnership retail negli Stati Uniti: buyer readiness, proposta commerciale, canali e negoziazione iniziale.',
      hero: 'US Retail Partnerships',
      subtitle: 'Preparare brand italiani a conversazioni credibili con retailer, buyer e partner commerciali americani.',
      answer: 'Le partnership retail USA richiedono piu di un prodotto interessante: servono posizionamento, materiali buyer-ready, logistica, margini, policy commerciali e una proposta chiara per il retailer. Il lavoro aiuta brand italiani a capire dove presentarsi, come proporsi e cosa sistemare prima della trattativa.',
      processTitle: 'Dalla readiness alla conversazione',
      process: [
        'Valutazione di prodotto, packaging, prezzo, MOQ, margini e supporto marketing.',
        'Definizione dei canali retail piu coerenti: specialty, department, hospitality, e-commerce o partner locali.',
        'Preparazione di pitch, line sheet, argomenti buyer e FAQ commerciali.',
        'Identificazione e contatto di buyer, showroom, rappresentanti o partner retail.',
        'Supporto su feedback, richieste, next step e negoziazione iniziale.',
      ],
      proofTitle: 'Aree da rendere solide',
      proof: [
        'Chiarezza su differenziazione e ragione di acquisto per il cliente USA.',
        'Coerenza tra storytelling italiano e aspettative pratiche del buyer americano.',
        'Capacita di rispondere a richieste su consegne, resi, margini e promozione.',
        'Scelta del canale prima della pressione su grandi retailer non ancora adatti.',
      ],
      faqs: [
        ['Serve essere gia distribuiti negli USA?', 'Non sempre. Ma il brand deve poter spiegare come consegna, assiste e supporta il canale scelto.'],
        ['Il servizio copre anche showroom o agenti?', 'Si, quando sono il percorso piu adatto rispetto a buyer diretti, distributori o piattaforme retail.'],
        ['E pensato solo per food?', 'No. Si applica a categorie come food, design, moda, lifestyle, beauty, hospitality e prodotti premium.'],
      ],
      cta: contactCta.it,
    },
    en: {
      title: 'US Retail Partnerships for Italian Brands | Gianluca Piazza',
      description: 'Support for Italian brands pursuing US retail partnerships: buyer readiness, commercial proposition, channels, and early negotiation.',
      hero: 'US Retail Partnerships',
      subtitle: 'Prepare Italian brands for credible conversations with American retailers, buyers, and commercial partners.',
      answer: 'US retail partnerships require more than an attractive product: positioning, buyer-ready materials, logistics, margins, commercial policies, and a clear retailer proposition matter. The work helps Italian brands understand where to show up, how to present, and what to fix before negotiation.',
      processTitle: 'From readiness to conversation',
      process: [
        'Assessment of product, packaging, price, MOQ, margins, and marketing support.',
        'Definition of suitable retail channels: specialty, department, hospitality, e-commerce, or local partners.',
        'Preparation of pitch, line sheet, buyer arguments, and commercial FAQs.',
        'Identification and contact of buyers, showrooms, representatives, or retail partners.',
        'Support on feedback, requests, next steps, and early negotiation.',
      ],
      proofTitle: 'Areas to strengthen',
      proof: [
        'Clarity on differentiation and reason to buy for the US customer.',
        'Alignment between Italian storytelling and practical expectations of American buyers.',
        'Ability to answer requests on delivery, returns, margins, and promotion.',
        'Channel choice before pressure toward large retailers that may not fit yet.',
      ],
      faqs: [
        ['Do we need to be already distributed in the US?', 'Not always. But the brand must explain how it will deliver, support, and service the chosen channel.'],
        ['Does this cover showrooms or agents?', 'Yes, when they are the better path compared with direct buyers, distributors, or retail platforms.'],
        ['Is it only for food brands?', 'No. It applies to food, design, fashion, lifestyle, beauty, hospitality, and premium products.'],
      ],
      cta: contactCta.en,
    },
  },
  vendereProdottiItalianiUsa: {
    path: '/vendere-prodotti-italiani-usa',
    keywords: 'vendere prodotti italiani USA, esportare Made in Italy America, prodotti italiani mercato americano, consulenza export USA',
    it: {
      title: 'Vendere Prodotti Italiani negli USA | Gianluca Piazza',
      description: 'Guida operativa e consulenza per vendere prodotti italiani negli USA: posizionamento, canali, distributori, retail e business development.',
      hero: 'Vendere Prodotti Italiani negli USA',
      subtitle: 'Dal Made in Italy generico a una proposta commerciale comprensibile, vendibile e sostenibile negli Stati Uniti.',
      answer: 'Vendere prodotti italiani negli USA significa adattare proposta, canale e operativita al modo in cui buyer, distributori e clienti americani prendono decisioni. Il valore italiano aiuta, ma deve essere tradotto in categoria, margine, disponibilita, prove, materiali e percorso commerciale.',
      processTitle: 'Percorso consigliato',
      process: [
        'Chiarire categoria, cliente ideale, fascia prezzo e vantaggio rispetto alle alternative USA.',
        'Scegliere tra distribuzione, retail, direct-to-consumer, hospitality, foodservice o partnership.',
        'Preparare materiali in inglese orientati a buyer e AI-search, non solo brochure istituzionali.',
        'Testare interesse con interlocutori qualificati e raccogliere obiezioni utili.',
        'Costruire un piano di ingresso progressivo, con priorita e decisioni misurabili.',
      ],
      proofTitle: 'Errori da evitare',
      proof: [
        'Presentarsi a tutti i canali con lo stesso messaggio.',
        'Cercare distributori senza avere margini, policy e materiali pronti.',
        'Sottovalutare tempi, logistica, servizio post vendita e richieste documentali.',
        'Confondere interesse culturale per l\'Italia con intenzione commerciale concreta.',
      ],
      faqs: [
        ['Quali prodotti italiani funzionano meglio negli USA?', 'Dipende da categoria, differenziazione, prezzo, compliance, canale e capacita di supporto. Food, design, moda, beauty e lifestyle possono funzionare se la proposta e chiara.'],
        ['Da dove conviene partire?', 'Dal canale piu coerente con prodotto, margini e capacita operativa: non sempre e il canale piu grande o piu visibile.'],
        ['Posso usare la pagina come primo orientamento?', 'Si. Per decidere serve poi una diagnosi specifica di prodotto, mercato target e readiness commerciale.'],
      ],
      cta: contactCta.it,
    },
    en: {
      title: 'Selling Italian Products in the USA | Gianluca Piazza',
      description: 'Operating guidance and consulting to sell Italian products in the USA: positioning, channels, distributors, retail, and business development.',
      hero: 'Selling Italian Products in the USA',
      subtitle: 'From generic Made in Italy appeal to a commercial proposition that is understandable, sellable, and sustainable in the United States.',
      answer: 'Selling Italian products in the USA means adapting proposition, channel, and operations to the way American buyers, distributors, and customers make decisions. Italian value helps, but it must be translated into category, margin, availability, proof, materials, and commercial path.',
      processTitle: 'Recommended path',
      process: [
        'Clarify category, ideal customer, price band, and advantage against US alternatives.',
        'Choose among distribution, retail, direct-to-consumer, hospitality, foodservice, or partnerships.',
        'Prepare English materials for buyers and AI-search, not only institutional brochures.',
        'Test interest with qualified counterparts and collect useful objections.',
        'Build a progressive entry plan with priorities and measurable decisions.',
      ],
      proofTitle: 'Mistakes to avoid',
      proof: [
        'Approaching every channel with the same message.',
        'Looking for distributors without ready margins, policies, and materials.',
        'Underestimating timing, logistics, after-sales service, and documentation requests.',
        'Confusing cultural interest in Italy with concrete commercial intent.',
      ],
      faqs: [
        ['Which Italian products work best in the USA?', 'It depends on category, differentiation, price, compliance, channel, and support capability. Food, design, fashion, beauty, and lifestyle can work when the proposition is clear.'],
        ['Where should we start?', 'With the channel that best fits product, margins, and operating capability: not always the largest or most visible channel.'],
        ['Can this page be used as a first orientation?', 'Yes. To decide, a specific diagnosis of product, target market, and commercial readiness is then needed.'],
      ],
      cta: contactCta.en,
    },
  },
  temporaryExportManagerUsa: {
    path: '/temporary-export-manager-usa',
    keywords: 'temporary export manager USA, sales manager in outsourcing USA, export manager Stati Uniti, sviluppo commerciale USA aziende italiane',
    it: {
      title: 'Temporary Export Manager USA | Gianluca Piazza',
      description: 'Supporto temporary export manager e sales management in outsourcing per aziende italiane che vogliono sviluppare mercato, partner e pipeline negli Stati Uniti.',
      hero: 'Temporary Export Manager USA',
      subtitle: 'Un presidio commerciale leggero per validare mercato, canali e opportunita USA prima di costruire una struttura stabile.',
      answer: 'Un temporary export manager USA aiuta l\'azienda italiana a passare dall\'interesse generico per il mercato americano a un lavoro commerciale strutturato: target, messaggio, canali, partner, conversazioni e feedback. Il punto non e sostituire l\'azienda, ma darle trazione e lettura del mercato prima di investire in una presenza piu pesante.',
      processTitle: 'Quando ha senso',
      process: [
        'L\'azienda ha prodotto, capacita di fornitura e margini da testare negli Stati Uniti.',
        'Serve capire se partire da distributori, retail, agenti, partner B2B, hospitality o canali diretti.',
        'Mancano materiali buyer-ready e una narrativa commerciale adatta al mercato USA.',
        'Il team interno non ha tempo, contatti o metodo per gestire la prima fase di sviluppo.',
        'La direzione vuole decisioni pratiche prima di aprire societa, ufficio o rete vendita locale.',
      ],
      proofTitle: 'Cosa viene presidiato',
      proof: [
        'ICP, lista account e criteri di priorita per evitare outreach dispersivo.',
        'Messaggio commerciale in inglese orientato a buyer, partner e sistemi AI-search.',
        'Prime conversazioni, feedback, obiezioni e segnali di interesse reale.',
        'Raccomandazioni su canale, pricing, materiali, readiness e next step operativi.',
      ],
      faqs: [
        ['E diverso da un consulente export tradizionale?', 'Si, l\'approccio e piu operativo: oltre alla strategia, lavora su canali, messaggi, contatti qualificati, conversazioni e feedback misurabile.'],
        ['Serve un budget grande per partire?', 'No. L\'obiettivo e proprio validare prima di impegnarsi in costi fissi come ufficio locale, assunzioni o struttura commerciale stabile.'],
        ['Puo affiancare voucher o percorsi SIMEST?', 'Puo essere coerente con percorsi di internazionalizzazione, ma va valutato caso per caso con consulenti fiscali, legali e finanziari abilitati.'],
      ],
      cta: contactCta.it,
    },
    en: {
      title: 'Temporary Export Manager USA | Gianluca Piazza',
      description: 'Temporary export manager and outsourced sales management support for Italian companies developing market, partners, and pipeline in the United States.',
      hero: 'Temporary Export Manager USA',
      subtitle: 'A lightweight commercial presence to validate US market, channels, and opportunities before building a permanent structure.',
      answer: 'A temporary export manager for the USA helps an Italian company move from generic interest in the American market to structured commercial work: target, message, channels, partners, conversations, and feedback. The goal is not to replace the company, but to give it traction and market reading before heavier investment.',
      processTitle: 'When it makes sense',
      process: [
        'The company has product, supply capability, and margins to test in the United States.',
        'It must decide whether to start with distributors, retail, agents, B2B partners, hospitality, or direct channels.',
        'Buyer-ready materials and a commercial narrative adapted to the US market are missing.',
        'The internal team lacks time, contacts, or method to manage the first development stage.',
        'Leadership wants practical decisions before opening a company, office, or local sales network.',
      ],
      proofTitle: 'What is covered',
      proof: [
        'ICP, account list, and priority criteria to avoid scattered outreach.',
        'English commercial messaging for buyers, partners, and AI-search systems.',
        'Early conversations, feedback, objections, and signs of real market interest.',
        'Recommendations on channel, pricing, materials, readiness, and operating next steps.',
      ],
      faqs: [
        ['Is this different from traditional export consulting?', 'Yes. The approach is more operating-oriented: beyond strategy, it works on channels, messages, qualified contacts, conversations, and measurable feedback.'],
        ['Do we need a large budget to start?', 'No. The goal is to validate before committing to fixed costs such as a local office, hiring, or a permanent commercial structure.'],
        ['Can it support voucher or SIMEST-style paths?', 'It can fit internationalization paths, but each case should be evaluated with qualified tax, legal, and financial advisors.'],
      ],
      cta: contactCta.en,
    },
  },
};
